-- Role Table
CREATE TABLE role
(
    role_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP     NOT NULL,
    created_by VARCHAR2(255) NOT NULL,
    updated_at TIMESTAMP     NOT NULL,
    updated_by VARCHAR2(255) NOT NULL,

    PRIMARY KEY (role_id),
    CONSTRAINT uk_role_name UNIQUE (name)
);

-- User Table
CREATE TABLE platform_user
(
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    role_id         NUMBER,
    full_name       VARCHAR2(255) NOT NULL,
    last_name       VARCHAR2(255) NOT NULL,
    first_name      VARCHAR2(255) NOT NULL,
    username        VARCHAR2(255) NOT NULL,
    password        VARCHAR2(255) NOT NULL,
    email           VARCHAR2(100) NOT NULL,
    status          VARCHAR2(255) NOT NULL,
    created_at      TIMESTAMP     NOT NULL,
    created_by      VARCHAR2(255) NOT NULL,
    updated_at      TIMESTAMP     NOT NULL,
    updated_by      VARCHAR2(255) NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT fk_user_role_id FOREIGN KEY (role_id) REFERENCES role (role_id) ON DELETE CASCADE
);

-- Privilege Table
CREATE TABLE privilege
(
    privilege_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name                VARCHAR2(255) NOT NULL,

    PRIMARY KEY (privilege_id),
    CONSTRAINT uk_privilege_name UNIQUE (name)
);

-- Privilege_Assignment Table
CREATE TABLE privilege_assignment
(
    role_id      NUMBER        NOT NULL,
    privilege_id NUMBER        NOT NULL,
    type         VARCHAR2(255) NOT NULL,
    assigned_at  TIMESTAMP     NOT NULL,

    CONSTRAINT pk_privilege_assignment PRIMARY KEY (role_id, privilege_id),
    CONSTRAINT fk_privilege_assignment_role_id FOREIGN KEY (role_id) REFERENCES role (role_id) ON DELETE CASCADE,
    CONSTRAINT fk_privilege_assignment_privilege_id FOREIGN KEY (privilege_id) REFERENCES privilege (privilege_id) ON DELETE CASCADE
);
